schema_version: 20180708
name: uppercase
version: 1.0.42
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.116
run_image: fnproject/fn-java-fdk:jre11-1.0.116
cmd: io.helidon.examples.microprofile.oci.functions.OCIType::apply
triggers:
- name: uppercase
  type: http
  source: /uppercase
